name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@49c3e4e92c52e7f8392712a9267bbe71c5ab30e5 # v1.19.0
        with:
          node-version: lts/*
          cache: true

      - name: Version & publish packages
        run: vpr tegami ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
