name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1.12.0
        with:
          node-version: lts/*
          cache: true

      - name: Version & publish packages
        run: vpr tegami ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
